repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hakancelik96/unimport
    rev: 004b5dd0c8112330275beb52c4ccfce016a4b945
    hooks:
      - id: unimport
        name: unimport (Remove unused imports)
        args: [--remove, --include-star-import, --ignore-init, --gitignore]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--in-place, --pre-summary-newline, --close-quotes-on-newline]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.202'
    hooks:
      - id: ruff
        args: ["--force-exclude", "--fix"]
